// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkrdonkjuwbxjhjdgyym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrcmRvbmtqdXdieGpoamRneXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDk2NDcsImV4cCI6MjA2NTQ4NTY0N30.efZvzUFf4eAF_EvMId4S4jVz9ZXZV-vWyjA8XcfyxzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);